### ISSUE TITLE
Pass config.yaml variables in via environment

### ISSUE THREAD

**Issue by marccampbell** [anchore/anchore-engine#1]
It would be nice to be able to reference an environment variable in the config.yaml, especially for sensitive data (postgres credentials).

I'd expect to be able to use the same syntax that docker-compose does, and be able support either of these:

```yaml
  database:
    db_connect: '${DATABASE_URI}'
    db_connect_args:
      timeout: 120
      ssl: False
    db_pool_size: 30
    db_pool_max_overflow: 100
```

or 

```yaml
  database:
    db_connect: 'postgresql+pg8000://postgres:${DATABASE_PASSWORD}@anchore-db:5432/postgres'
    db_connect_args:
      timeout: 120
      ssl: False
    db_pool_size: 30
    db_pool_max_overflow: 100
```
