### ISSUE TITLE
Registries: Failure to add ECR registry

### ISSUE THREAD

**Issue by gambol99** [anchore/anchore-engine#118]
**Is this a request for help?**: 
NO
**Is this a BUG REPORT or a FEATURE REQUEST?**:
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
```shell
$ anchore-cli --version
anchore-cli, version 0.3.1
image: docker.io/anchore/anchore-engine:v0.3.1 in kubernetes
```
 
**What happened**:

While trying to add an ECR registy using 

```shell
$ anchore-cli registry add --registry-type=awsecr ACCOUNT_ID.dkr.ecr.eu-west-2.aws.amazon.com AWS_ACCESS_ID AWS_SECRET_KEY
Error: cannot refresh credentials for supplied registry, with supplied credentials - exception: too many values to unpack (expected 6)

retrying using the cli 
$ export AWS_REGION=eu-west-2
$ export AWS_ACCESS_KEY_ID=AWS_ACCESS_ID
$ export AWS_SECRET_ACCESS_KEY=AWS_SECRET_KEY
$ aws ecr get-authorization-token  | jq '.authorizationData[].authorizationToken' -r 
works fine
```

**What did you expect to happen**:

Expected to add the registry

**Any relevant log output from /var/log/anchore**:
```shell
ervice:api] 2018-12-14 12:54:59+0000 [-] "10.250.5.199" - - [14/Dec/2018:12:54:58 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12"
[service:api] 2018-12-14 12:55:00+0000 [_GenericHTTPChannelProtocol,98,10.10.161.8] [PoolThread-twisted.internet.reactor-0] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service catalog for url: http://catalog.anchore.svc.cluster.local:8082/v1/system/registries. Response: {'httpcode': 406, 'anchore_error_raw': 'b\'{\\n  "detail": {},\\n  "httpcode": 406,\\n  "message": "cannot refresh credentials for supplied registry, with supplied credentials - exception: too many values to unpack (expected 6)"\\n}\\n\'', 'anchore_error_json': {'detail': {}, 'httpcode': 406, 'message': 'cannot refresh credentials for supplied registry, with supplied credentials - exception: too many values to unpack (expected 6)'}}
```

**What docker images are you using**:
`docker.io/anchore/anchore-engine:v0.3.1`

**How to reproduce the issue**:
Adding an ECR registry

**Anything else we need to know**:
It appears that whenever i take a pod is leaves an orphaned service.

```shell
$ anchore-cli system status | sort
Engine Code Version: 0.3.1
Engine DB Version: 0.0.8
Service analyzer (analyzer-55d4cb9bcb-88v2l, https://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-55d4cb9bcb-dwkq7, https://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-55d4cb9bcb-vdk4c, https://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-57467f96c7-fdjc9, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-57467f96c7-mkn8z, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-57467f96c7-nmdtq, https://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-57467f96c7-p4r9f, https://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-7b5687b9c5-4x9tq, http://analyzer.anchore.svc.cluster.local:8084): down (unavailable)
Service analyzer (analyzer-7b5687b9c5-59zdl, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-7b5687b9c5-8z5hg, http://analyzer.anchore.svc.cluster.local:8084): up
Service analyzer (analyzer-7b5687b9c5-9mbql, http://analyzer.anchore.svc.cluster.local:8084): up
Service analyzer (analyzer-7b5687b9c5-fgzc5, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-7b5687b9c5-nxpkt, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service analyzer (analyzer-7b5687b9c5-xc2g8, http://analyzer.anchore.svc.cluster.local:8084): down (orphaned)
Service apiext (api-55bd65985b-2zzcb, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-55bd65985b-n2cvp, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-57c48b67ff-drdtw, http://api.anchore.svc.cluster.local:8228): down (unavailable)
Service apiext (api-57c48b67ff-kbncq, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-49tbt, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-dqthm, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-h5x5f, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-hxjst, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-mq564, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-nz6fv, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-q6nk4, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-wlg7q, https://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-5f6bbdb565-wwfmt, http://api.anchore.svc.cluster.local:8228): down (orphaned)
Service apiext (api-6c67994d5f-fqvtj, http://api.anchore.svc.cluster.local:8228): up
Service apiext (api-6c67994d5f-xfcph, http://api.anchore.svc.cluster.local:8228): up
Service catalog (catalog-55f7c9664-br6pr, http://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-55f7c9664-vjrl2, https://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-55f7c9664-wgjr6, https://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-64499b5f5f-8bnzh, https://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-6485c5d784-2sxt4, http://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-6485c5d784-n6rvp, http://catalog.anchore.svc.cluster.local:8082): down (orphaned)
Service catalog (catalog-6485c5d784-pn68q, http://catalog.anchore.svc.cluster.local:8082): up
Service catalog (catalog-6485c5d784-q4tz7, http://catalog.anchore.svc.cluster.local:8082): down (unavailable)
Service policy_engine (policy-6589999df7-8cpz5, http://policy.anchore.svc.cluster.local:8087): up
Service policy_engine (policy-6589999df7-bnmhl, http://policy.anchore.svc.cluster.local:8087): down (orphaned)
Service policy_engine (policy-6589999df7-r248n, http://policy.anchore.svc.cluster.local:8087): down (unavailable)
Service policy_engine (policy-6589999df7-ww67q, http://policy.anchore.svc.cluster.local:8087): down (orphaned)
Service policy_engine (policy-74774c4f8d-rrhvb, https://policy.anchore.svc.cluster.local:8087): down (orphaned)
Service policy_engine (policy-74774c4f8d-znq7r, http://policy.anchore.svc.cluster.local:8087): down (orphaned)
Service policy_engine (policy-7b6db86d4c-6b2jn, https://engine-policy:8087): down (orphaned)
Service simplequeue (simplequeue-648cddf688-2fdlk, https://simplequeue.anchore.svc.cluster.local:8083): down (orphaned)
Service simplequeue (simplequeue-76f6dd989f-2rwm6, http://simplequeue.anchore.svc.cluster.local:8083): down (unavailable)
Service simplequeue (simplequeue-76f6dd989f-9g86r, http://simplequeue.anchore.svc.cluster.local:8083): down (orphaned)
Service simplequeue (simplequeue-76f6dd989f-lstnb, http://simplequeue.anchore.svc.cluster.local:8083): up
Service simplequeue (simplequeue-76f6dd989f-vkr4f, http://simplequeue.anchore.svc.cluster.local:8083): down (orphaned)
Service simplequeue (simplequeue-c9cdb6cdc-6j5q6, https://simplequeue.anchore.svc.cluster.local:8083): down (orphaned)
Service simplequeue (simplequeue-c9cdb6cdc-p7dqf, http://simplequeue.anchore.svc.cluster.local:8083): down (orphaned)
```

Configuration:

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: anchore-engine
  name: anchore-engine
data:
  ANCHORE_DB_HOST: db
  ANCHORE_DB_NAME: anchore
  ANCHORE_DB_USER: anchoreengine
  ANCHORE_LOG_LEVEL: "INFO"
  config.yaml: |
    # Anchore Service Configuration File from ConfigMap
    allow_awsecr_iam_auto: false
    auto_restart_services: false
    cleanup_images: {}
    host_id: ${ANCHORE_POD_NAME}
    internal_ssl_verify: false
    log_level: ${ANCHORE_LOG_LEVEL}
    service_dir: /anchore_service_config
    tmp_dir: /scratch
    metrics:
      enabled: true

    # Uncomment if you have a local endpoint that can accept
    # notifications from the anchore-engine, as configured below

    # Configure what feeds to sync. The 'admin' anchoreIO credentials are used if present, but not required.
    # The 'anonymous' user is used for the sync otherwise.
    # The sync will hit http://ancho.re/feeds, if any outbound firewall config needs to be set in your environment.
    feeds:
      sync_enabled: true
      selective_sync:
        # If enabled only sync specific feeds instead of all that are found.
        enabled: true
        feeds:
          # Vulnerabilities feed is the feed for distro cve sources (redhat, debian, ubuntu, oracle, alpine....)
          vulnerabilities: true
          # NVD Data is used for non-distro CVEs (jars, npm, etc) that are not packaged and released by distros as rpms, debs, etc
          nvd: true
          # Warning: enabling the package sync causes the service to require much
          #   more memory to do process the significant data volume. We recommend at least 4GB available for the container
          packages: false
          # Enabling snyk syncs snyk vulnerability data from an on-premise anchore enterprise feeds service. Please contact
          # anchore support for finding out more about this service
          snyk: false
      client_url: 'https://ancho.re/v1/account/users'
      token_url: 'https://ancho.re/oauth/token'
      anonymous_user_username: anon@ancho.re
      anonymous_user_password: PASS
      connection_timeout_seconds: 3
      read_timeout_seconds: 60

    default_admin_password: ${ANCHORE_ADMIN_PASSWORD}
    default_admin_email: admin@example.com

    credentials:
      database:
        db_connect: 'postgresql+pg8000://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}'
        db_connect_args:
          timeout: 120
          ssl: false
        db_pool_size: 30
        db_pool_max_overflow: 30

    services:
      apiext:
        enabled: true
        require_auth: true
        endpoint_hostname: api.anchore.svc.cluster.local
        listen: '0.0.0.0'
        port: 8228
        ssl_enable: false
        ssl_cert: /certs/tls.pem
        ssl_key: /certs/tls-key.pem
      analyzer:
        analyzer_driver: 'nodocker'
        cycle_timer_seconds: 1
        cycle_timers:
          image_analyzer: 5
        enabled: true
        endpoint_hostname: analyzer.anchore.svc.cluster.local
        listen: '0.0.0.0'
        max_threads: 1
        port: 8084
        require_auth: true
        ssl_enable: false
        ssl_cert: /certs/tls.pem
        ssl_key: /certs/tls-key.pem
      catalog:
        enabled: true
        require_auth: true
        endpoint_hostname: catalog.anchore.svc.cluster.local
        listen: '0.0.0.0'
        port: 8082
        cycle_timer_seconds: '1'
        cycle_timers:
          analyzer_queue: 1
          image_watcher: 3600
          notifications: 30
          policy_eval: 3600
          repo_watcher: 60
          service_watcher: 15
          vulnerability_scan: 14400
        event_log:
          notification:
            enabled: true
            level:
            - error

        ssl_enable: false
        ssl_cert: /certs/tls.pem
        ssl_key: /certs/tls-key.pem

        archive:
          compression:
            enabled: true
            min_size_kbytes: 100
          storage_driver:
            config: {}
            name: db

      simplequeue:
        enabled: true
        require_auth: true
        endpoint_hostname: simplequeue.anchore.svc.cluster.local
        listen: '0.0.0.0'
        port: 8083
        ssl_enable: false
        ssl_cert: /certs/tls.pem
        ssl_key: /certs/tls-key.pem

      policy_engine:
        enabled: true
        require_auth: true
        endpoint_hostname: policy.anchore.svc.cluster.local
        listen: '0.0.0.0'
        port: 8087
        cycle_timer_seconds: 1
        cycle_timers:
          feed_sync: 14400
          feed_sync_checker: 3600

        ssl_enable: false
        ssl_cert: /certs/tls.pem
        ssl_key: /certs/tls-key.pem
```
