### ISSUE TITLE
Feature: add support for SNS notifications as alternative to webhooks

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#123]
For an AWS user, having the ability to send notifications to one or more SNS topics rather than a simple webhook will enable many integrations and notification formats, so that Anchore can inject notifictions into existing streams/systems.

As the current webhook configuration is global, so too would be the SNS config, but instead of configuring different webhook urls, the user could provide ARNs for the SNS topic for delivery and the username/password set would support either access/secret key combos or a username of: "aws_role" and password of the role arn to assume using the credentials found in the current execution environment (e.g. instance or task profile).

Example:
```
webhooks:
  webhook_user: 'aws_role"
  webhook_pass: 'arn:aws:iam::123456789012:role/anchore-sns-push'
  ssl_verify: False
  general:
    url: 'arn:aws:sns:us-west-2:123456789012:anchore-general-notifications'
  policy_eval:
    url: 'arn:aws:sns:us-west-2:123456789012:anchore-policy-notifications'
    #webhook_user: 'aws_role'
    #webhook_pass: 'arn:aws:iam::123456789012:role/anchore-sns-policy-push'
  event_log:
    # Uncomment the event_log section in addition to configuring this webhook to receive event log notifications
    url: 'arn:aws:sns:us-west-2:123456789012:anchore-event-notifications'
```

The notification payload will be the existing webhook payload
