### ISSUE TITLE
[ERROR] no 'services' definition in configuration file

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#146]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:

Anchore Engine 0.3.2
Helm chart 0.11.0

 
**What happened**:

I get the following error in all pods:

```
[MainThread] [anchore_engine.configuration.localconfig/validate_config()] [ERROR] no 'services' definition in configuration file
[MainThread] [anchore_manager.cli.service/start()] [ERROR] Error: cannot load local configuration: invalid configuration: details - no 'services' definition in configuration file
```

**What did you expect to happen**:

I expect the pod to run correctly

**Any relevant log output from /var/log/anchore**:

No such log in the pod.
However...

Anchore engine is deployed through Helm with minimal values.yaml to define the admin pass and email, and the postgresql endpoint because I'm using an RDS. Here is the values.yaml used for Helm deployment (secret values replaced by XXXXXXXXXXXXXXX):

```yaml
# FROM https://github.com/helm/charts/blob/master/stable/anchore-engine/values.yaml

anchoreGlobal:

  # Sets the password & email address for the default anchore-engine admin user.
  defaultAdminPassword: XXXXXXXXXXXXXXX
  defaultAdminEmail: XXXXXXXXXXXXXXX

#  ingress:
#    enabled: true
#    annotations: 
#      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#      nginx.ingress.kubernetes.io/rewrite-target: /
#      kubernetes.io/ingress.allow-http: "false"
#      kubernetes.io/ingress.class: nginx
#      # kubernetes.io/tls-acme: true
#    tls: 
#    # Secrets must be manually created in the namespace.
#    #  - secretName: chart-example-tls
#       - hosts:
#          - anchore.k8s-prd.cloud.620nm.net

postgresql:
  # To use an external DB, uncomment & set 'enabled: false'
  # externalEndpoint, postgresUser, postgresPassword & postgresDatabase are required values for external postgres
  enabled: false
  postgresUser: anchoreengine
  postgresPassword: XXXXXXXXXXXXXXX
  postgresDatabase: anchore
  # Specify an external (already existing) postgres deployment for use.
  # Set to the host and port. eg. mypostgres.myserver.io:5432
  externalEndpoint: XXXXXXXXXXXXXXX:5432
```

The generated configmap is this one:

```yaml
11:50 $ kubectl describe cm anchore-anchore-engine
Name:         anchore-anchore-engine
Namespace:    anchore
Labels:       app=anchore-anchore-engine
              chart=anchore-engine-0.11.0
              heritage=Tiller
              release=anchore
Annotations:  <none>

Data
====
ANCHORE_DB_HOST:
----
XXXXXXXXXXXXXXX:5432
ANCHORE_DB_NAME:
----
anchore
ANCHORE_DB_USER:
----
anchoreengine
config.yaml:
----
# Anchore Service Configuration File from ConfigMap

service_dir: /anchore_service_config
tmp_dir: /scratch
log_level: INFO
cleanup_images: 

allow_awsecr_iam_auto: false
host_id: "${ANCHORE_POD_NAME}"
internal_ssl_verify: false
auto_restart_services: false

metrics:
  enabled: false

# Uncomment if you have a local endpoint that can accept
# notifications from the anchore-engine, as configured below
#


# Configure what feeds to sync. The 'admin' anchoreIO credentials are used if present, but not required.
# The 'anonymous' user is used for the sync otherwise.
# The sync will hit http://ancho.re/feeds, if any outbound firewall config needs to be set in your environment.
feeds:
  sync_enabled: true
  selective_sync:
    # If enabled only sync specific feeds instead of all that are found.
    enabled: true
    feeds:
      # Vulnerabilities feed is the feed for distro cve sources (redhat, debian, ubuntu, oracle, alpine....)
      vulnerabilities: true
      # NVD Data is used for non-distro CVEs (jars, npm, etc) that are not packaged and released by distros as rpms, debs, etc
      nvd: true
      # Warning: enabling the package sync causes the service to require much
      #   more memory to do process the significant data volume. We recommend at least 4GB available for the container
      packages: false
      # Enabling snyk syncs snyk vulnerability data from an on-premise anchore enterprise feeds service. Please contact
      # anchore support for finding out more about this service
      snyk: false
  client_url: "https://ancho.re/v1/account/users"
  token_url: "https://ancho.re/oauth/token"
  anonymous_user_username: anon@ancho.re
  anonymous_user_password: XXXXXXXXXXXXXXX
  connection_timeout_seconds: 3
  read_timeout_seconds: 60

default_admin_password: ${ANCHORE_ADMIN_PASSWORD}
default_admin_email: XXXXXXXXXXXXXXX

credentials:
  database:
    db_connect: "postgresql+pg8000://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}"
    db_connect_args:
      timeout: 120
      ssl: false
    db_pool_size: 30
    db_pool_max_overflow: 30

services:
  apiext:
    enabled: true
    require_auth: true
    endpoint_hostname: anchore-anchore-engine-api
    listen: 0.0.0.0
    port: 8228
    ssl_enable: false
    ssl_cert: "/certs/tls.crt"
    ssl_key: "/certs/tls.key"
  analyzer:
    enabled: true
    require_auth: true
    endpoint_hostname: anchore-anchore-engine-analyzer
    listen: 0.0.0.0
    port: 8084
    cycle_timer_seconds: 1
    cycle_timers:
      image_analyzer: 5
      
    max_threads: 1
    analyzer_driver: 'nodocker'
    ssl_cert: "/certs/tls.crt"
    ssl_key: "/certs/tls.key"
    ssl_enable: false
  catalog:
    enabled: true
    require_auth: true
    endpoint_hostname: anchore-anchore-engine-catalog
    listen: 0.0.0.0
    port: 8082
    cycle_timer_seconds: 1
    cycle_timers:
      analyzer_queue: 1
      image_watcher: 3600
      notifications: 30
      policy_eval: 3600
      repo_watcher: 60
      service_watcher: 15
      vulnerability_scan: 14400
      
    ssl_enable: false
    ssl_cert: "/certs/tls.crt"
    ssl_key: "/certs/tls.key"
    event_log:
      notification:
        enabled: true
        level:
        - error
      
    archive:
      compression:
        enabled: true
        min_size_kbytes: 100
      storage_driver:
        config: {}
        name: db
      
  simplequeue:
    enabled: true
    require_auth: true
    endpoint_hostname: anchore-anchore-engine-simplequeue
    listen: 0.0.0.0
    port: 8083
    ssl_enable: false
    ssl_cert: "/certs/tls.crt"
    ssl_key: "/certs/tls.key"
  policy_engine:
    enabled: true
    require_auth: true
    endpoint_hostname: anchore-anchore-engine-policy
    listen: 0.0.0.0
    port: 8087
    cycle_timer_seconds: 1
    cycle_timers:
      feed_sync: 14400
      feed_sync_checker: 3600
      
    ssl_cert: "/certs/tls.crt"
    ssl_key: "/certs/tls.key"
    ssl_enable: false
Events:  <none>
```

Looks like to me that services exist in the configuration file.
I connected to the pods, and checked that /config/config.yaml file content is the same as the config map, and the file exists, and the content is the same.

So I don't know why this error happens, message looks like to be incoherent with configuration.
