### ISSUE TITLE
Support policy and whitelist mappings by detected image distro, version, and flavor

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#185]
Since vulnerability sources used for matching an image depend on the detected distro and version of an image, it would be helpful to also be able to use that metadata in mapping policies and whitelists in the bundle.

This would allow keeping distro-specific whiteilsts and matching all appropriate images without having to use information that isn't directly linked to the content (like tags and repos).

Implemented as additional optional fields in the mapping rules definition. Below is a snippet of the swagger.yaml with new fields:
```
  MappingRule:
    ...
      distro_name:
        type: string
        description: The distro name of the image, as detected in the analysis of an image (e.g. redhat, centos, debian, alpine...)
      distro_flavor:
        type: string
        enum:
        - rhel
        - debian
        - alpine
        - busybox
        description: The flavor of distro, used for determining package manager type and sometimes used in the vulnerability source mapping
      distro_version:
        type: string
        description: Version string w/wildcard support for version matches (e.g. "7.*", "3.8")
    ...
```

If present in a mapping rule, all conditions must match for the rule to be a match and the policy/whitelists of that rule to be applied to the image during policy evaluation.
