### ISSUE TITLE
Re-enable the ability for anchore-engine to use alternate back-end (localfs) for archive documents

### ISSUE THREAD

**Issue by nurmi** [anchore/anchore-engine#19]
Anchore-engine <= 0.1.5 only supported the option to store archive documents in the main DB, even though early versions also supported a local FS option as well.  We want to bring back this ability, and in addition the new implementation will better support future additional archive storage drivers to be added.

**Comment by nurmi** [comment]
This feature has been brought back in, implemented in a way that should be easier to extend with additional storage drivers moving forward.  With the new code, default behavior is unchanged (if config.yaml has 'use_db: True' or '#use_db: ...' then the default is to use the DB for archive documents.  The new params are keys that can be set for the 'catalog' service in config.yaml to select the driver and other options.  The two available drivers are 'db' (default) and 'localfs' (which will use the DB for archive document metadata but store the contents on the provided local filesystem, which is recommended to be an external volume)

example config to enable the localfs driver:

```
  catalog:
    enabled: True
    require_auth: True
    endpoint_hostname: 'anchore-engine'
    listen: '0.0.0.0'
    port: 8082
    #use_db: True
    archive_driver: 'localfs'
    archive_data_dir: '/workspace/archive_documents'
    ...
    ...
```

commit b11671cf3f9f7024f648afa6cd508e1787e9e5a4
Author: Daniel Nurmi <nurmi@anchore.com>
Date:   Wed Jan 3 14:03:30 2018 -0800
