### ISSUE TITLE
How to add a private a private registry say on loalhost:50000 to anchore-client?

### ISSUE THREAD

**Issue by nehaj27** [anchore/anchore-engine#207]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
NONE

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli --version anchore-cli, version 0.4.0
 
**What happened**:
I am unable to add a private registry for scanning.

**What did you expect to happen**:
Registry was deployed using the following commands:
```
mkdir Infrastructure
cd Infrastructure/
mkdir Registry
cd Registry/
```
vim docker-compose.yml

```
version: '3.0'

services:
  my-registry:
    image: registry:latest
    container_name: my-registry
    volumes:
      - registry:/var/lib/registry
    ports:
      - "50000:5000"
    restart: unless-stopped
volumes:
  registry:

```
```
docker-compose up -d
docker login localhost:50000
docker tag nmap-dist:latest localhost:50000/nmap-dist:latest && docker push localhost:50000/nmap-dist:latest
```

**Any relevant log output from /var/log/anchore**:
```
anchore-cli registry add 172.19.0.1:50000/v2/_catalog nehajainiitbhilai iitbhilai1234
```
Error: cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://172.19.0.1:50000,nehajainiitbhilai) - exception: HTTPSConnectionPool(host='172.19.0.1', port=50000): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))
HTTP Code: 406
Detail: {u'error_codes': []}

**What docker images are you using**:
nmap-dist, nmap image built on distroless.

**How to reproduce the issue**:

**Anything else we need to know**:
