### ISSUE TITLE
Policy gate and triggers for regexes on retrieved files from analysis

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#279]
This is an extension of the work in: #264 tracked as a different check rather than a negative check in the existing files gate. Storing a file and performing file-specific checks rather than scan entire images for regex matches is much more efficient and enables more sophisticated checks. 

Use the existing file retrieval mechanism in the analyzers which stores specific files in the analysis for processing of their raw content in policy evaluation. One example of this is the /etc/passwd checks in the "passwd_file" gate. Then provide a new gate+triggers to query regexes on those specific retrieved files. This allows for future application-specific handling of certain files. Currently the configuration is set at install time, but eventually that will be runtime-configurable as well (which files to retrieve). However, those changes (runtime config) are outside the scope of this work.

This mitigates the performance penalty of using the content/secret search which checks every file for a regex. As that list of regexes grows the performance hit gets larger.

existing section of default analyzer_config.yaml:
```
retrieve_files:
  file_list:
    - '/etc/passwd'
```
update it to:
```
retrieve_files:
  max_allowed_size: 100KB
  file_list:
    - '/etc/passwd'
   # HTTPD configs
   - '/etc/apache2/httpd.conf'
   - '/etc/apache2/apache2.conf'
   - '/etc/httpd/httpd.conf'
   - '/etc/httpd/conf/httpd.conf'
  # NGINX configs
   - '/etc/nginx/nginx.conf'
```
The max_allowed_size is a change to ensure a malicious file that is very large cannot be used to cause resource issues in anchore and that value should easily cover most valid configs or allow the user to specify a range that has acceptable risk.

New gate: "saved_file_checks"
Trigger: "regex"
Parameters:

file_path: e.g "/etc/httpd/httpd.conf"
regex: e.g. ".MaxKeepAliveRequests."
check_type: "match", "not_matched"
Will also add an API call to external API to allow showing the list of retrieved files and their content, for an image. This is necessary to enable policy authoring and validation.
