### ISSUE TITLE
Unable to enable webhooks

### ISSUE THREAD

**Issue by mikeklein** [anchore/anchore-engine#46]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:

anchore-cli, version 0.1.9
Name: anchore-engine
Version: 0.1.9
 
**What happened**:

Updated config.yaml as follows:

```
webhooks:
  ssl_verify: False
  general:
    url: 'http://localhost:8080/general/<notification_type>'
  tag_update:
    url: 'http://localhost:8080/tag_update'
  policy_eval:
    url: 'http://localhost:8080/policy_eval'
  error_event:
    url: 'http://localhost:8080/error_event/'
```
I also marked True for all subscr types for centos:latest tag

**What did you expect to happen**:

Some messages in logs regarding webhook invocation when images are scanned, etc. Not only are logs silent but my app doesn't show callbacks being hit.

**Any relevant log output from /var/log/anchore**:

Is silent regarding all webhooks except kubernetes. When I try to disable the k8s webhook logs go bonkers trying to restart it, etc.

**What docker images are you using**:

Yours

**How to reproduce the issue**:
Update config.yaml for webhooks per above and see they aren't called.

**Anything else we need to know**:
Nope!

**Comment by mikeklein** [comment]
After upgrading to 2.1 I am now seeing analysis_updates coming in via webhook.

**Comment by zhill** [comment]
Hi @mikeklein, Glad its working. analysis_update is the webhook that fires when analysis is complete, the others are a little more tricky to force to fire because things have to change in the system to trigger it (new image for an existing tag, policy evaluation state change, etc).

Right now the error_event type isn't being used so don't expect any evens from that, but we're in the processing of adding those so it will be used very soon.

Are you unblocked then or is there still an issue we need to look at?

**Comment by mikeklein** [comment]
Spoke too soon. Noticed a few errors during startup and started anew with fresh install of 2.1.

At no point do I see webhook notifications occuring and callbacks made to my app with endpoints exposed for config.yaml urls. The following is my config.yaml:

```
webhooks:
  ssl_verify: False
  general:
    url: 'http://localhost:8080/general/<notification_type>/<userId>'
  policy_eval:
    url: 'http://localhost:8080/policy_eval/<userId>'
```
