### ISSUE TITLE
Image content command's help text is incomplete

### ISSUE THREAD

**Issue by luhring** [anchore/anchore-engine#590]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Bug

**Version of Anchore Engine and Anchore CLI if applicable**:

```
[anchore@anchore-testing-anchore-engine-api-59f588694-tmgr5 enterprise]$ anchore-cli --version
anchore-cli, version 0.8.0
[anchore@anchore-testing-anchore-engine-api-59f588694-tmgr5 enterprise]$ pip3 show anchore-engine
Name: anchore-engine
Version: 0.8.1
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: yosai, requests, python-swiftclient, swagger-spec-validator, prettytable, Werkzeug, zope.interface, zope.component, pathlib, psutil, Flask, SQLAlchemy, ijson, python-dateutil, pytz, Twisted, jsonschema, passlib, psycopg2-binary, boto3, typing, treelib, retrying, semantic-version, toastedmarshmallow, Click, watchdog, python-keystoneclient, connexion, urllib3, prometheus-client, PyYAML, Authlib, prometheus-flask-exporter, six, pg8000
```

**What happened**:

```
[anchore@anchore-testing-anchore-engine-api-59f588694-tmgr5 enterprise]$ anchore-cli image content -h
Usage: anchore-cli image content [OPTIONS] INPUT_IMAGE [CONTENT_TYPE]

  INPUT_IMAGE: Input image can be in the following formats: Image Digest,
  ImageID or registry/repo:tag

  CONTENT_TYPE: The content type can be one of the following types:

    - os: Operating System Packages

    - npm: Node.JS NPM Module

    - gem: Ruby GEM

    - files: Files

Options:
  -h, --help  Show this message and exit.
```

**What did you expect to happen**:

This list of possible types is incomplete. I expected either the full list of possible content types to be displayed, or else not show a list at all.

[Dan Nurmi suggested](https://anchore.slack.com/archives/C1DMGFP3J/p1598454912258800?thread_ts=1598454134.253200&cid=C1DMGFP3J) an elegant solution to this.

**Any relevant log output from /var/log/anchore**: n/a

**What docker images are you using**: `docker.io/anchore/enterprise-dev:v2.4.0-rc1`

**How to reproduce the issue**: Run `anchore-cli image content -h`

**Anything else we need to know**:
