### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by Kaitsh** [anchore/anchore-engine#6]
Hi anchore team,

I wanted to get started with the webhooks but somehow it doesn't work. I used [webhook.site](http://webhook.site) as an testing endpoint. But there is no request done by anchore-engine. 

This is my webhook config:
```yaml
webhooks:
#  webhook_user: 'user'
#  webhook_pass: 'pass'
  ssl_verify: False
  notification_retry_timeout: 30
  general:
    url: 'http://webhook.site/f96f3a0b-14fa-4c91-b4b8-a75b8c6d999e/general/<notification_type>'
#  policy_eval:
#    url: 'http://localhost:9090/policy_eval/<userId>'
#    webhook_user: 'mehuser'
#    webhook_pass: 'mehpass'
# special webhook for FATAL service events - system will store in DB if not enabled here
  error_event:
    url: 'http://webhook.site/f96f3a0b-14fa-4c91-b4b8-a75b8c6d999e/error_event/'
```
In the log I found nothing about a failed request.
All subscriptions are activated and I manually updated an image, pushed it to the registry and added it to the engine to reanalyze it.

Thanks,
Kaitsh
