### ISSUE TITLE
Ability to set pool_recycle args for db connection handling

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#641]
**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Feature Request

If this is a FEATURE REQUEST, please:
Add ability to specify more db connection pool settings, including at least the ability to set the `pool_recycle` timeout to ensure stale connections are recycled before being used and causing an error if the connection was closed by the server or some intermediate network gear (e.g. a load balancer).

This is useful for cases where load balancers have short idle connection timeouts like 5-10 minutes.

Should add a generic `db_engine_args` section and handlers for config.yaml to allow per-deployment customization.
e.g.
```
credentials:
  database:
    db_connect: ...
    db_connect_args:
      timeout: 120
      ssl: false
    db_pool_size: 30
    db_pool_max_overflow: 100
    db_engine_args:
      <key-values to pass>
      pool_recycle: 600
```
