### ISSUE TITLE
ContentMatchTrigger in file gate incorrectly compares encoded values with decoded ones

### ISSUE THREAD

**Issue by zburstein** [anchore/anchore-engine#756]
**Explanation of Issue***
The ContentMatchTrigger in file gate will fail to properly fire due to logical errors with how the user supplied `regex_name` param is compared to the values in the artifact_analysis record. See [file](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/policy/gates/files.py). The `regex_name` string is encoded and stored in a var called `match_decoded`. The values from the artifact_analysis are decoded and then there are multiple conditions that end up comparing the encoded values with the decoded ones that will never result in the trigger to properly fire even when the values both decoded are identical.

**How to reproduce the issue**:
1.  create the following analyzer config block:
```
content_search:
  match_params:
    - MAXFILESIZE=10000
    - STOREONMATCH=n
  regexp_match:
    - "AWS_ACCESS_KEY=(?i).*aws_access_key_id( *=+ *).*(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9]).*"
    - "AWS_SECRET_KEY=(?i).*aws_secret_access_key( *=+ *).*(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]).*"
    - "PRIV_KEY=(?i)-+BEGIN(.*)PRIVATE KEY-+"
    - "DOCKER_AUTH=(?i).*\"auth\": *\".+\""
    - "API_KEY=(?i).*api(-|_)key( *=+ *).*(?<![A-Z0-9])[A-Z0-9]{20,60}(?![A-Z0-9]).*"
```

2. In the policy bundle create a file gate with ContentMatchTrigger and set the `regex_name` to be `AWS_ACCESS_KEY`. 

3. Run an image analysis on `anchore/test_images:secret_match_fake_v1` and evaluate it with policy bundle

Because the image content_search analyzer will match the `AWS_ACCESS_KEY`, this should cause the trigger to fire, but it passes
